package fr.cesi.BasicWebServiceSpring.entity;;
// Generated 20 juin 2017 19:05:55 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name="address"
    ,catalog="wood_db"
)
public class Address  implements java.io.Serializable {


     private int id;
     private User user;
     private Buyer buyer;
     private String line1;
     private String line2;
     private String line3;
     private String postalCode;
     private String city;
     private String country;
     private String label;

    public Address() {
    }

	
    public Address(int id, User user) {
        this.id = id;
        this.user = user;
    }
    public Address(int id, User user,Buyer buyer, String line1, String line2, String line3, String postalCode, String city, String country, String label) {
       this.id = id;
       this.user = user;
       this.buyer = buyer;
       this.line1 = line1;
       this.line2 = line2;
       this.line3 = line3;
       this.postalCode = postalCode;
       this.city = city;
       this.country = country;
       this.label = label;
    }
   
    @Id
    @GenericGenerator(name = "kaugen", strategy = "increment")
    @GeneratedValue(generator = "kaugen")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="use_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="buy_id", nullable=false)
    public Buyer getBuyer() {
        return this.buyer;
    }
    
    public void setBuyer(Buyer buyer) {
        this.buyer = buyer;
    }
    
    @Column(name="line_1", length=10)
    public String getLine1() {
        return this.line1;
    }
    
    public void setLine1(String line1) {
        this.line1 = line1;
    }
    
    @Column(name="line_2", length=10)
    public String getLine2() {
        return this.line2;
    }
    
    public void setLine2(String line2) {
        this.line2 = line2;
    }
    
    @Column(name="line_3", length=10)
    public String getLine3() {
        return this.line3;
    }
    
    public void setLine3(String line3) {
        this.line3 = line3;
    }
    
    @Column(name="postal_code", length=10)
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    
    @Column(name="city", length=10)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="country", length=10)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    
    @Column(name="label", length=10)
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }




}


