package fr.cesi.BasicWebServiceSpring.entity;

;
// Generated 20 juin 2017 19:05:55 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * Buyer generated by hbm2java
 */


@Entity
@Table(name = "buyer",
        catalog = "wood_db"
)
public class Buyer implements java.io.Serializable {

    private int id;
    private User user;
    private String firstName;
    private String lastName;
    private String email;
    private Date birthDate;
    private Set<Piece> categories = new HashSet<Piece>(0);
    private Set<Address> addresses = new HashSet<Address>(0);
    private Set<Phones> phoneses = new HashSet<Phones>(0);

    public Buyer() {
    }

    public Buyer(int id, User user) {
        this.id = id;
        this.user = user;
    }

    public Buyer(int id, User user, String firstName, String lastName, Date birthDate, String email, String password, Set<Piece> categories, Set<Address> addresses, Set<Phones> phoneses) {
        this.id = id;
        this.user = user;
        this.firstName = firstName;
        this.lastName = lastName;
        this.birthDate = birthDate;
        this.email = email;
        this.categories = categories;
        this.addresses = addresses;
        this.phoneses = phoneses;
    }

    @Id
    @GenericGenerator(name = "kaugen", strategy = "increment")
    @GeneratedValue(generator = "kaugen")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by_user_id", nullable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Column(name = "first_name", length = 256)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "last_name", length = 256)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "birth_date", length = 10)
    public Date getBirthDate() {
        return this.birthDate;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    @Column(name = "email", length = 256)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "buyer")
    public Set<Piece> getCategories() {
        return this.categories;
    }

    public void setCategories(Set<Piece> categories) {
        this.categories = categories;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "buyer")
    public Set<Address> getAddresses() {
        return this.addresses;
    }

    public void setAddresses(Set<Address> addresses) {
        this.addresses = addresses;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "buyer")
    public Set<Phones> getPhoneses() {
        return this.phoneses;
    }

    public void setPhoneses(Set<Phones> phoneses) {
        this.phoneses = phoneses;
    }

}
