/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.cesi.BasicWebServiceSpring.entity;

/**
 *
 * @author mgonzalez
 */

// Generated 20 juin 2017 19:05:55 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Phones generated by hbm2java
 */
@Entity
@Table(name = "phones",
        catalog = "wood_db"
)
public class Phones implements java.io.Serializable {

    private int number;
    private User user;
    private Buyer buyer;
    private Byte country;
    private Boolean verified;

    public Phones() {
    }

    public Phones(int number, User user) {
        this.number = number;
        this.user = user;
    }

    public Phones(int number, User user,Buyer buyer, Byte country, Boolean verified) {
        this.number = number;
        this.user = user;
        this.buyer = buyer;
        this.country = country;
        this.verified = verified;
    }

    @Id
    @Column(name = "number", unique = true, nullable = false, precision = 8, scale = 0)
    public int getNumber() {
        return this.number;
    }

    public void setNumber(int number) {
        this.number = number;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "use_id", nullable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "buy_id", nullable = false)
    public Buyer getBuyer() {
        return this.buyer;
    }

    public void setBuyer(Buyer buyer) {
        this.buyer = buyer;
    }
    
    @Column(name = "country", precision = 2, scale = 0)
    public Byte getCountry() {
        return this.country;
    }

    public void setCountry(Byte country) {
        this.country = country;
    }

    @Column(name = "verified")
    public Boolean getVerified() {
        return this.verified;
    }

    public void setVerified(Boolean verified) {
        this.verified = verified;
    }

}