package fr.cesi.BasicWebServiceSpring.entity;
// Generated 20 juin 2017 19:05:55 by Hibernate Tools 3.2.2.GA

import fr.cesi.BasicWebServiceSpring.entity.Address;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user",
        catalog = "wood_db"
)
public class User implements java.io.Serializable {

    private int id;
    private String firstName;
    private String lastName;
    private Date birthDate;
    private String email;
    private String password;
    private Set<Buyer> buyers = new HashSet<Buyer>(0);
    private Set<Address> addresses = new HashSet<Address>(0);
    private Set<Phones> phoneses = new HashSet<Phones>(0);

    public User() {
    }

    public User(int id) {
        this.id = id;
    }

    public User(int id, String firstName, String lastName, Date birthDate, String email, String password, Set <Buyer> buyers, Set<Address> addresses, Set<Phones> phoneses) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.birthDate = birthDate;
        this.email = email;
        this.password = password;
        this.buyers = buyers;
        this.addresses = addresses;
        this.phoneses = phoneses;
    }

    @Id
    @GenericGenerator(name = "kaugen", strategy = "increment")
    @GeneratedValue(generator = "kaugen")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

  

    @Column(name = "first_name", length = 256)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "last_name", length = 256)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "birth_date", length = 10)
    public Date getBirthDate() {
        return this.birthDate;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    @Column(name = "email", length = 256)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "password", length = 256)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "user")
    public Set<Buyer> getBuyers() {
        return this.buyers;
    }

    public void setBuyers(Set<Buyer> buyers) {
        this.buyers = buyers;
    }
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "user")
    public Set<Address> getAddresses() {
        return this.addresses;
    }

    public void setAddresses(Set<Address> addresses) {
        this.addresses = addresses;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "user")
    public Set<Phones> getPhoneses() {
        return this.phoneses;
    }

    public void setPhoneses(Set<Phones> phoneses) {
        this.phoneses = phoneses;
    }

}
